# Generated by Django 2.1.3 on 2018-12-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tnc',
            field=models.BooleanField(default=True),
        ),
    ]
