# Generated by Django 2.1.3 on 2018-12-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_tnc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tnc',
        ),
    ]
