# Generated by Django 2.1.3 on 2019-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
    ]
