# Generated by Django 2.1.3 on 2019-01-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190122_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_pic',
            field=models.ImageField(blank=True, default='static/cover.jpg', upload_to='cover_pic/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/profile.jpg', upload_to='profile_pic/'),
        ),
    ]
