# Generated by Django 2.1.3 on 2019-01-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190124_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_pic',
            field=models.ImageField(blank=True, default='cover.jpg', upload_to='cover_pic/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.jpg', upload_to='profile_pic/'),
        ),
    ]
