# Generated by Django 2.1.3 on 2018-12-24 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.CharField(default='Anonymous', max_length=100)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='gallery/image/')),
                ('label', models.CharField(default='Image', max_length=100)),
                ('descriptions', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_360', models.BooleanField(default=False)),
                ('image_360Link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Image Gallery',
            },
        ),
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Image Category',
                'verbose_name_plural': 'Image Categories',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gallery.ImageCategory'),
        ),
    ]
