# Generated by Django 2.1.3 on 2019-01-04 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190104_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='contributor',
            field=models.ForeignKey(default='Anon', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
