# Generated by Django 2.1.3 on 2019-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20190104_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
