# Generated by Django 2.1.3 on 2019-01-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20190104_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='descriptions',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
