# Generated by Django 2.1.3 on 2019-01-19 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0006_auto_20190105_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='pic_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
