# Generated by Django 2.1.3 on 2019-01-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_gallery_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image_360Link',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_360',
        ),
    ]
