# Generated by Django 2.1.3 on 2019-01-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20190131_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, help_text='THIS is field is AUTO-GENERATED keep it empty', unique=True),
        ),
    ]
