# Generated by Django 2.1.3 on 2019-02-01 06:37

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20190131_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecategory',
            name='representative_image',
            field=stdimage.models.StdImageField(blank=True, upload_to='category_images/'),
        ),
    ]
